name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12.3"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # - name: Run Black Formatter on Updated File
    #   run: |
    #     changed_files=$(git diff --name-only --diff-filter=ACMRTUXB HEAD^1 HEAD | grep -E '\.py$' | xargs)
    #     if [ -n "$changed_files" ]; then
    #       black $changed_files
    #     else
    #       echo "No Python files changed."
    #     fi

    # - name: Run linters
    #   run: |
    #     black --check tests/
  
    - name: Run tests
      run: |
        pytest

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
